### ISSUE TITLE
Problem with initial seeding of database

### ISSUE THREAD

**Issue by cmluciano** [jnf/blinder#81]
Upon initial seed I receive an error about a role not being present

```
FATAL:  role "blinder" does not exist
/Users/cmlucian/projects/blinder/db/schema.rb:17:in `block in <top (required)>'
/Users/cmlucian/projects/blinder/db/schema.rb:14:in `<top (required)>'
Tasks: TOP => db:schema:load
```

**Comment by cmluciano** [comment]
This was simply an issue with the blinder uname and password not being present in my local db
